### ISSUE TITLE
Just a question? If I had to build a web app...

### ISSUE THREAD

**Issue by bright-spark** [szepeviktor/infrastructure-for-hosting-web-applications#1]
### Just a note:

> Ever consider using GitHub repos combined with Cloudflare?

There are workers, pages, caching, DDoS protection, Web Application Firewall, CI/CD, DNS, CDN, Mail, System / Web Analytics and more thrown in.  

_You can make use of a very generous completely free developer account._

**Try it today!** 

- Here is a sample PWA I wrote [theradio.plus](https://theradio.plus)
- Reach me on Twitter [Paperstorm](https://twitter.com/paperstorm) if you need more information.

**Comment by szepeviktor** [comment]
Thank you @bright-spark!

If you are thinking about a project in the long-term (let's say 5 years) you have to think about how your service providers operate.
Cloudflare is a company I would never recommend to anyone.

**Comment by bright-spark** [comment]
Why would you say that? I have had nothing but good support and constant advances over the past 3 years? And 0% downtime...

**Comment by szepeviktor** [comment]
- Cloudflare has a free plan -> lot of bad guys are on Cloudflare
- Cloudflare participates in PRISM program
- Cloudflare "owns you" - e.g. there is no SSL certificate revocation

I like [doing everything by hand](https://github.com/szepeviktor/debian-server-tools/blob/master/Onboarding.md#specialized-infrastructure-providers) so I can have total control of the web applications given to me.

ps. I spend 24 hours a day watching web applications run so I see much more details

**Comment by bright-spark** [comment]
Ok, I understand your point of view. I still beg to differ although if you can educate me I would appreciate the help. Problem is the free tier is instrumental in my design pattern and in South Africa the beginner programmer I’m aiming at empowering and teaching, can’t afford lunch or transport, not to mention development expenses for learning costs for a home baked idea to make their own.

**Comment by szepeviktor** [comment]
You must know that giving an advise without having a budget is really-really hard. You have to prepare for problems: you pay or you work!

My ultimate goal is to have such a nice infrastructure and application that produces almost no issues.
